#!/bin/bash

echo "############################################"
echo "Setup is done"
echo "You can access the traefik dashboard at:"
echo "  http://localhost:8888/dashboard/"
echo "############################################"
